package com.example.joe.musicalstructure;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.ListView;

import java.util.ArrayList;

public class SongsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.music_list);

        ArrayList<Music> musicList = new ArrayList<>();
        musicList.add(new Music("Blackout City", "By: Anamanaguchi", R.drawable.dawnmetropolis));
        musicList.add(new Music("Jetpack Blues, Sunset Hues", "By: Anamanaguchi", R.drawable.dawnmetropolis));
        musicList.add(new Music("Dawn Metropolis", "By: Anamanaguchi", R.drawable.dawnmetropolis));
        musicList.add(new Music("Danger Mountain", "By: Anamanaguchi", R.drawable.dawnmetropolis));
        musicList.add(new Music("Overarrow", "By: Anamanaguchi", R.drawable.dawnmetropolis));
        musicList.add(new Music("Tempest, Teamwork, Triumph (at Sea)", "By: Anamanaguchi", R.drawable.dawnmetropolis));
        musicList.add(new Music("Endless Fantasy", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Japan Air", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Echobo", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Planet", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Viridian Genesis", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("John Hughes", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Prom Night (Ft. Bianca Raquel)", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Interlude (Gymnopedie No. 1)", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Akira", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("SPF 420", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Interlude (Total Tea Time)", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Meow", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Canal Paradise", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Snow Angels", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("In The Basement", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("U n Me", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Space Wax America", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("EVERYTHING EXPLODES", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Interlude (STILL SPLODIN THO)", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Pastel Flags", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Bosozoku GF", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("(T-T)b", "By: Anamanaguchi", R.drawable.endlessfantasy));
        musicList.add(new Music("Space Oddity", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Unwashed and Somewhat Slightly Dazed", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Don't Sit Down", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Letter to Hermione", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Cygnet Committee", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Janine", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("An Occasional Dream", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Wild Eyed Boy From Freecloud", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("God Knows I'm Good", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Memory of a Free Festival", "By: David Bowie", R.drawable.spaceoddity));
        musicList.add(new Music("Watch That Man", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Aladdin Sane", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Drive In Saturday", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Panic in Detroit", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Cracked Actor", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Time", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("The Prettiest Star", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Let's Spend the Night Together", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("The Jean Genie", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Lady Grinning Soul", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("A Lad in Vain [aka: Zion]", "By: David Bowie", R.drawable.aladdinsane));
        musicList.add(new Music("Rosalyn", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Here Comes The Night", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("I Wish You Would", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("See Emily Play", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Everything's Alright", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("I Can't Explain", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Friday On My Mind", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Sorrow", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Don't Bring Me Down", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Shapes Of Things", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Anyway, Anyhow, Anywhere", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Where Have All The Good Times Gone", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Port of Amsterdam", "By: David Bowie", R.drawable.pinups));
        musicList.add(new Music("Young Americans", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Win", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Fascination", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Right", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Somebody Up There Likes Me", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Across the Universe (Ft. John Lennon)", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Can You Hear Me", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Fame (Ft. John Lennon)", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Who Can I Be Now?", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("It's Gonna Be Me", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("It's Gonna Be Me (With Strings)", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("1984", "By: David Bowie", R.drawable.youngamericans));
        musicList.add(new Music("Murmaider", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Go Into the Water", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Awaken", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Bloodrocuted", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Go Forth and Die", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Fansong", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Beter Metal Snake", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("The Lost Vikings", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Thunderhorse", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Briefcase Full of Guts", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Birthday Dethday", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Hatredcopter", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Castratikron", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Face Fisted", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Dethharmonic", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Deththeme", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Duncan Hills Coffee Jingle", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Blood Ocean", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Murdertrain a Comin'", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Pickles Intro", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Kill You", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Hatredy", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Dethklok Gets in Tune", "By: Dethklok", R.drawable.thedethalbum));
        musicList.add(new Music("Bloodlines", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("The Gears", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Burn the Earth", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Laser Cannon Deth Sentence", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Black Fire Upon Us", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Dethsupport", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("The Cyborg Slayers", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("I Tamper With the Evidence at the Murder Site of Odin", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Murmaider II: The Water God", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Comet Song", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Symmetry", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("Volcano", "By: Dethklok", R.drawable.dethalbum2));
        musicList.add(new Music("I Ejaculate Fire", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Crush the Industry", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Andromeda", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("The Galaxy", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Starved", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Killstardo Abominate", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Ghostqueen", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Impeach God", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Biological Warfare", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Skyhunter", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("The Hammer", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Rejoin", "By: Dethklok", R.drawable.dethalbum3));
        musicList.add(new Music("Death on Two Legs", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("Lazing on a Sunday Afternoon", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("I'm in Love with My Car", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("You're My Best Friend", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("'39", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("Sweet Lady", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("Seaside Rendezvous", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("The Prophet's Song", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("Love of My Life", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("Good Company", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("Bohemian Rhapsody", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("God Save the Queen", "By: Queen", R.drawable.anightattheopera));
        musicList.add(new Music("We Will Rock You", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("We Are The Champions", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Sheer Heart Attack", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("All Dead, All Dead", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Spread Your Wings", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Fight From The Inside", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Get Down, Make Love", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Sleeping On The Sidewalk", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Who Needs You", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("It's Late", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("My Melancholy Blues", "By: Queen", R.drawable.newsoftheworld));
        musicList.add(new Music("Flash's Theme", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("In the Space Capsule (The Love Theme)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Ming's Theme (In The Court of Ming the Merciless)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("The Ring (Hypnotic Seduction of Dale)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Football Fight", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("In the Death Cell (Love Theme Reprise)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Execution of Flash", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("The Kiss (Aura Resurrects Flash)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Arboria (Planet of the Tree Men)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Escape from the Swamp", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Flash to the Rescue", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Vultan's Theme (Attach of the Hawk Men)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Battle Theme", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("The Wedding March", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Marriage of Dale and Ming (And Flash Approaching)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Crash Dive on Mingo City", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Flash's Theme Reprise (Victory Celebrations)", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("The Hero", "By: Queen", R.drawable.flashgordon));
        musicList.add(new Music("Staying Power", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Dancer", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Back Chat", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Body Language", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Action This Day", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Put Out The Fire", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Life Is Real (Song for Lennon)", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Calling All Girls", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Las Palabras De Amor (The Words of Love)", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Cool Cat", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Under Pressure (Ft. David Bowie)", "By: Queen", R.drawable.hotspace));
        musicList.add(new Music("Anthem", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("Best I Can", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("Beneath, Between And Behind", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("By-Tor And The Snow Dog", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("Fly By Night", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("Making Memories", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("Rivendell", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("In The End", "By: Rush", R.drawable.flybynight));
        musicList.add(new Music("Cygnus X-1, Book II: Hemispheres", "By: Rush", R.drawable.hemispheres));
        musicList.add(new Music("Circumstances", "By: Rush", R.drawable.hemispheres));
        musicList.add(new Music("The Trees", "By: Rush", R.drawable.hemispheres));
        musicList.add(new Music("La Villa Strangiato (An Exercise in Self-Indulgence)", "By: Rush", R.drawable.hemispheres));
        musicList.add(new Music("The Spirit of Radio", "By: Rush", R.drawable.permanentwaves));
        musicList.add(new Music("Freewill", "By: Rush", R.drawable.permanentwaves));
        musicList.add(new Music("Jacob's Ladder", "By: Rush", R.drawable.permanentwaves));
        musicList.add(new Music("Entre Nous", "By: Rush", R.drawable.permanentwaves));
        musicList.add(new Music("Different Strings", "By: Rush", R.drawable.permanentwaves));
        musicList.add(new Music("Natural Science", "By: Rush", R.drawable.permanentwaves));
        musicList.add(new Music("Mine", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Sparks Fly", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Back To December", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Speak Now", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Dear John", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Mean", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("The Story of Us", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Never Grow Up", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Enchanted", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Better Than Revenge", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Innocent", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Haunted", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Last Kiss", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Long Live", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Ours", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("If This Was a Movie", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("Superman", "By: Taylor Swift", R.drawable.speaknow));
        musicList.add(new Music("State of Grace", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Red", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Treacherous", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("I Knew You Were Trouble", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("All Too Well", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("22", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("I Almost Do", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("We Are Never Ever Getting Back Together", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Stay Stay Stay", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("The Last Time (Ft. Gary Lightbody)", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Holy Ground", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Sad Beautiful Tragic", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("The Lucky One", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Everything Has Changed (Ft. Ed Sheeran)", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("StarLight", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Begin Again", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("The Moment I Knew", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Come Back... Be Here", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Girl at Home", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Treacherous (Original Demo Recording)", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("Red (Original Demo Recording)", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("State Of Grace (Original Demo Recording)", "By: Taylor Swift", R.drawable.red));
        musicList.add(new Music("...Ready for It?", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("End Game (Ft. Ed Sheeran & Future)", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("I Did Something Bad", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Don't Blame Me", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Delicate", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Look What You Made Me Do", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("So It Goes...", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Gorgeous", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Getaway Car", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("King of My Heart", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Dancing With Our Hands Tied", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Dress", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("This Is Why We Can't Have Nice Things", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("Call It What You Want", "By: Taylor Swift", R.drawable.reputation));
        musicList.add(new Music("New Year's Day", "By: Taylor Swift", R.drawable.reputation));

        MusicAdapter adapter = new MusicAdapter(this, musicList);

        ListView listView = findViewById(R.id.list);

        listView.setAdapter(adapter);

    }
}
